
trigger: 
  branches:
    include:
    - '*'
lockBehavior: sequential
  pool:
    vmImage: Ubuntu-latest

  jobs:
  - job: Job1
    steps:
    - script: echo Hey Stage A4!
  - job: Job2
    steps:
    - script: echo Hey Stage B3!
  - job: Job3
    steps:
    - script: echo Hey Stage C3!
